#:kivy 1.10.0


<WindowManager>:
    HomeWindow:
        id: home
    SecondWindow:
        id: second

<HomeWindow>:
    name: '__home__'
    
    Label:
        text: "Bangla Sign language Detection"
        pos_hint: {'center_x':.5, 'center_y':.8}
        size_hint: 1, 1
        font_size: 24
        
    Label:
        text: root.manager.cr
        pos_hint: {'center_x':.95, 'center_y':.01}
        size_hint: 1, 1
        font_size: 14
    
    Label:
        text: root.manager.sign_text
        pos_hint: {'center_x':.8, 'center_y':.3}
        size_hint: 1, 1
        font_size: 18
    
    
    Image:
        source: root.manager.image_path
        pos_hint: {'center_x':.3, 'center_y':.22}
        size_hint: .4,.4
    
    Image:
        source: root.manager.logo_path
        pos_hint: {'center_x':.5, 'center_y':.9}
        size_hint: .1,.1


    Button:
        
        id: add_image
        text: "Add Image"
        pos_hint: {'center_x':.5, 'center_y':.5}
        size_hint: .4, .1
        
        on_release:
            
            root.manager.transition.direction = "left"
    
    Button:
        id: detect_image
        text: "Detect Sign"
        pos_hint: {'center_x':.8, 'center_y':.22}
        size_hint: .2, .1
        
            
            
        
    
    

<SecondWindow>:
    name: '__second__'
    
    FileChooserIconView:
        id: file
        size_hint: .8, .5
        pos_hint: {'center_x':.5, 'center_y':.7}
        on_selection: 
            root.manager.image_path: file.path

    Button:
        id: done
        text: "Done"
        pos_hint: {'center_x':.5, 'center_y':.2}
        size_hint: .4, .2
        on_release:
            
            root.manager.transition.direction = "right"
            

    
    

